trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x' # Ajuste conforme sua versão do .NET

  - task: DotNetCoreCLI@2
    displayName: 'Build Blazor WASM'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'wwwroot' # Ajuste conforme sua estrutura
      output_location: 'wwwroot'
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
